# -*- coding: utf-8 -*-
"""Parcial 20/11/2024

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ORDMyiN0r20ocYKxS3FnYhRqs-81iYrg

# Notebook Adquicisión y tratamiento de datos
"""

#Importamos las librerias que vayamos a usar.
import pandas as pd     #librería principal para la carga y el análisis de datos.

import glob             #librería para la gestión de ficheros.
import numpy as np      #nos proporciona métodos de gestión de arrays.

from google.colab import drive
drive.mount('/content/drive')

path_file="/content/drive/MyDrive/precio_mes_combustible_20240904.csv"
df=pd.read_csv(path_file, sep=",", header=0)

print(df.head()) # esto es para leer

all_files = glob.glob("/content/drive/MyDrive/precio_mes_combustible_20240904.csv") #Podremos visualisar las filas y columnas d

file_list = []
for f in all_files:

    # Changed pd.read_excel to pd.read_csv since the file is a CSV

    data = pd.read_csv(f, skiprows=0)
    data['source_file'] = f # nueva columna conteniendo el nombre del fichero leido
    file_list.append(data)
df = pd.concat(file_list)

df.shape

df.head()

df=df.rename(columns={"Periodo":"periodo","Mes":"mes","Codigo_departamento":"codigo_departamento","Departamento":"departamento","Codigo_municipio":"codigo_municipio","Municipio":"municipio","Nombre_comercial":"nombre_comercial","Bandera":"bandera","Direccion":"direccion","Producto":"producto","Precio":"precio","Estado":"estado","source_file":"Fecha"})
df.head(1)

df=df.replace(to_replace=r'.\(.+\)$', value='', regex=True) # Esto es para reemplazar signos o datos
df.head(1)

df.fecha=df.fecha.replace(regex={'p':'',r'\.+csv':''}) # Esto es para dejar solo numeros y eliminar texto; Eliminar cualquier archivo que tenga contenido.
df.head(1)

df.info()

estaciones_con_nan=df[df.isnull().any(axis=1)]['periodo'].unique()
df.drop(df[df['periodo'].isin(estaciones_con_nan)].index, inplace=True)
df.isna().sum()

df.iloc[:,np.r_[0:8,12:13]].describe()

df.filter(regex='^periodo*', axis=1).sample(5)

df.groupby('periodo').agg({col: 'mean' for col in df.select_dtypes(include=['number']).columns})

df.sort_values(by='periodo',ascending=False)[['fecha','codigo_departamento','mes','periodo']].head(3)

import matplotlib.pyplot as plt

sizes = [30, 25, 20, 1]

# GRAFICO CIRCULAR
labels = ['bandera', 'nombre_comercial', 'codigo_departamento', 'fecha']
colors = ['#ff9999', '#66b3ff', '#99ff99', '#ffcc99']
explode = (0, 0, 0, 0)
plt.pie(sizes, explode=explode, labels=labels, colors=colors,
        autopct='%1.1f%%', shadow=True, startangle=140)
plt.axis('equal')
plt.show()